# Site settings
title: Cole Judge
email: judge.52@osu.edu
url: colejudge.me
description: "'The greatest deception men suffer is from their own opinions.' - Leonardo Da Vinci"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Cole Judge

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/judge_cole
  - title: facebook
    url: https://www.facebook.com/cole.judge
  - title: stack-overflow
    url: #
  - title: bitbucket
    url: #
  - title: github
    url: https://github.com/Colejudge

# Build settings
markdown: kramdown
permalink: pretty
